### ISSUE TITLE
Output on file

### ISSUE THREAD

**Issue by rrotondo** [adoyle-h/bash-logger#3]
Hi, I tried to redirect output on a file but I can't make it working:
`source logger.sh "test"`
It creates a file test but it's empty. I still have output on stdout

**Comment by adoyle-h** [comment]
Can you provide Bash version by `bash --version` and the result of `type tee`?
I have published v0.2.1 just now. Please try the new version. @rrotondo

**Comment by rrotondo** [comment]
Hi, thank your for your fast response. I pulled the new version but I get the same result. Here what you asked: 
````
bash --version
GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

type tee
tee is /usr/bin/tee
````
Thank you

**Comment by adoyle-h** [comment]
@rrotondo Sorry, I cannot reproduce the issue both in Bash 5.0.11 with MacOS, and Bash 5.0.17 with Ubuntu docker image. You can try below steps for testing.

```
git clone https://github.com/adoyle-h/bash-logger.git
./test/logger_to_file.sh
cat test.log
```

Please provide a minimal, reproducible example so that I can debug it.

**Comment by rrotondo** [comment]
I tried this setting on my code: 
```
set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

readonly SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"

source "$SCRIPT_DIR"/../src/logger.sh "test.log"
```
but still I have the emty file. 

Despite this, the example you provided works so I think I do some different. I'll try on my own but I can close this. 
Thank you.
